### ISSUE TITLE
Public/private key encryption?

### ISSUE THREAD

**Issue by ghost** [foxed/CryptKeeper#1]
First, awesome repo name!

I'd love to really easily be able to generate a public/private key pair AND I'd like my friends to be able to use that public key to encrypt text that I can later decrypt with my private key ;)

**Comment by foxed** [comment]
ugh you're so demanding. but that is a great idea, thank youuuu!

**Comment by ghost** [comment]
Hey foxy fox! cleaning up stale issues I've left lying around. Hope all is good!
